---
title: "Class 4: Data structures and Importing Data"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    code_folding: show
    code_download: true

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
crashes_by_day = c(2020, 2241, 2327, 2285, 2380, 1866, 1664)
names(crashes_by_day) = c("Mon", "Tue", "Wed", "Thu",
                          "Fri", "Sat", "Sun")
crashes_by_day[2]                      # one position
```

```{r}
crashes_df = tibble::tibble(
  day     = names(crashes_by_day),
  crashes = crashes_by_day,
  busy    = crashes_by_day > 2000)
crashes_df$crashes                     # one column, as a vector
```

```{r}
nrow(crashes_df)             # how many rows?
ncol(crashes_df)             # how many columns?
colnames(crashes_df)         # what are they called?
typeof(crashes_df)           # what is it, underneath?

dplyr::glimpse(crashes_df)   # one line per column
```





```{r}
crashes_df[["crashes"]]                # the same vector, by name
```

```{r}
crashes_df[1:2, c("day", "crashes")]   # rows 1 to 2, two columns
```

```{r}
example_list = list(
  1:3,                    # integers 1, 2, 3
  "a",                    # one piece of text
  c(TRUE, FALSE, TRUE),   # three logicals
  c(2.3, 5.9)             # two decimals
)
str(example_list)         # the x-ray view
```
# Examining Job Ad
```{r job_ad}
job = list(
  title   = "Research Data Scientist, Magic Eye",
  company = "Google",
  salary  = list(min = 147000, max = 210000)
)
dplyr::glimpse(job)
str(job)

# Write one expression to extract each of
# 1. The company name.
company_name <- job$company # job[[2]]
# 2. The maximum salary.
max_salary <- job$salary$max # only if entities are named
# 3. The maximum salary again, using only [[ ]].
max_salary <- job[[3]][[2]]
# 4. The names of the elements in job.
names(job)

```

# Subsetting 
## Vectors

```{r vectors}
crashes_by_day = c(2020, 2241, 2327, 2285, 2380, 1866, 1664)
names(crashes_by_day) = c("Mon", "Tue", "Wed", "Thu",
                          "Fri", "Sat", "Sun")
crashes_by_day[2]                      # one position


crashes_by_day["Fri"]                  # by name

crashes_by_day[crashes_by_day > 2300]  # by condition

```

```{r jobs}
oh_jobs = readr::read_csv(
  file = "https://fred.stlouisfed.org/graph/fredgraph.csv?bgcolor=%23ebf3fb&chart_type=line&drp=0&fo=open%20sans&graph_bgcolor=%23ffffff&height=450&mode=fred&recession_bars=on&txtcolor=%23444444&ts=12&tts=12&width=1140&nt=0&thu=0&trc=0&show_legend=yes&show_axis_titles=yes&show_tooltip=yes&id=IHLIDXUSOH&scale=left&cosd=2021-08-21&coed=2026-08-28&line_color=%230073e6&link_values=false&line_style=solid&mark_type=none&mw=3&lw=3&ost=-99999&oet=99999&mma=0&fml=a&fq=Daily%2C%207-Day&fam=avg&fgst=lin&fgsnd=2020-02-01&line_index=1&transformation=lin&vintage_date=2026-09-02&revision_date=2026-09-02&nd=2020-02-01"
)

oh_jobs_base_r = read.csv(
  file = "https://fred.stlouisfed.org/graph/fredgraph.csv?bgcolor=%23ebf3fb&chart_type=line&drp=0&fo=open%20sans&graph_bgcolor=%23ffffff&height=450&mode=fred&recession_bars=on&txtcolor=%23444444&ts=12&tts=12&width=1140&nt=0&thu=0&trc=0&show_legend=yes&show_axis_titles=yes&show_tooltip=yes&id=IHLIDXUSOH&scale=left&cosd=2021-08-21&coed=2026-08-28&line_color=%230073e6&link_values=false&line_style=solid&mark_type=none&mw=3&lw=3&ost=-99999&oet=99999&mma=0&fml=a&fq=Daily%2C%207-Day&fam=avg&fgst=lin&fgsnd=2020-02-01&line_index=1&transformation=lin&vintage_date=2026-09-02&revision_date=2026-09-02&nd=2020-02-01"
)

oh_jobs
oh_jobs_base_r
```

