---
title: "Class06"
date: "2026-09-14"
output: 
  html_document: 
    toc: true
    toc_float: true
    number_sections: true
    code_download: true
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Hw 04
```{r hw04}
con = DBI::dbConnect(RSQLite::SQLite(), "../data/midwest_airbnb.db")
listings = DBI::dbReadTable(con, "listings")
```

## Kahoot
```{r kahoot}
run = readr::read_csv(
  "https://isa401-find-your-seat.vercel.app/api/export?section=A&run=13")
dplyr::glimpse(run)
```

# scout.db
```{r scout}
con = DBI::dbConnect(RSQLite::SQLite(),
                     "../data/scout.db")
DBI::dbListTables(con)
postings = DBI::dbReadTable(con, "scout_postings")
DBI::dbDisconnect(con)
dplyr::glimpse(postings[, c("title", "company",
  "location_state", "remote", "skills_json")])

first_cell = postings$skills_json[1]
cat(strtrim(first_cell, 60))   # base R: first 60 characters

skills = jsonlite::fromJSON(first_cell)
skills

DBI::dbDisconnect(con)

dplyr::glimpse(postings[, c("title", "company",
+  "location_state", "remote", "skills_json")])

```


